version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bookman
      SPRING_DATASOURCE_USERNAME: bookman
      SPRING_DATASOURCE_PASSWORD: bookman

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: bookman
      MYSQL_ROOT_PASSWORD: bookman
    ports:
      - "3306:3306"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - app
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bookman
      SPRING_DATASOURCE_USERNAME: bookman
      SPRING_DATASOURCE_PASSWORD: bookman
    command: ["mvn", "integration-test"]

